export const ActionTypes = {
    MENU_GENRE: 'MENU_GENRE',
    MENU_SEARCH: ' MENU_SEARCH',
    MOVIES_NOWPLAYING: 'MOVIES_NOWPLAYING',
    MOVIES_MOSTPOPULAR: 'MOVIES_MOSTPOPULAR',
    MOVIES_UPCOMING: 'MOVIES_UPCOMING',
    TVS_MOSTPOPULAR: 'TVS_MOSTPOPULAR',

    MOVIE_DETAILS: 'MOVIE_DETAILS',
    MOVIES_SIMILAR: 'MOVIES_SIMILAR',
}