export const ActionTypes = {
    MENU_GENRE: 'MENU_GENRE',
    MOVIES_NOWPLAYING: 'MOVIES_NOWPLAYING',
    MOVIES_MOSTPOPULAR: 'MOVIES_MOSTPOPULAR',
    MOVIES_UPCOMING: 'MOVIES_UPCOMING',
    TVS_MOSTPOPULAR: 'TVS_MOSTPOPULAR',
}